title : Hypermedia

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: hypermedia
destination: hypermedia

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 25
paginate_path: "/blog/page:num"

production_url : http://hypermedia.apievangelist.com

BASE_PATH : http://hypermedia.apievangelist.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
